### ISSUE TITLE
Save Causer when using LogsActivity trait

### ISSUE THREAD

**Issue by jariesdev** [spatie/laravel-activitylog#503] opened 2019-03-23 07:05 UTC
Im using the trait LogsActivity on my model and its saves the event happened but the causer is not saved. I have 2 users Model which is the Admin and Users Model. Did I miss something?

**Comment by Gummibeer** [comment] 2019-03-23 15:00
The causer is saved if the current guard knows about an user instance.
If you don't have an authenticated user in your guard this won't work.

If you want to customize the causer check the `tapActivity()` method.

**Comment by jariesdev** [comment] 2019-03-23 15:51
Sorry but do I tell the causer to use my guard('admin') ? I know that tapActivity() is used if I'm going to use activity() helper function.

**Comment by Gummibeer** [comment] 2019-03-23 20:15
```php
$this->authDriver = $config['activitylog']['default_auth_driver'] ?? $auth->getDefaultDriver();
```

With this config key you can set your default auth driver. Atm there is no way to change the used auth driver on runtime. But the `ActivityLogger` class is macroable and is bind as a service - so you can extend it.

The `tapActivity()` method is used for auto logged activities. For custom ones it's `tap()`.

**Comment by jny986** [comment] 2019-10-10 03:04
@jariesdev I would try something like the following to implement it into your system

On the model that you are logging activity add something like this

```
public function tapActivity(Activity $activity, string $eventName)
{
    if (Auth::check()) {
        $activity->causedBy = Auth::user();
    }
}
```
This if you auth is setup correctly should provide the causedBy to the activity logger.

I have created a pull request for this issue as well

**Comment by Gummibeer** [comment] 2021-04-27 08:57
I will close this issue even if v4 isn't released yet. But the task itself is done and I want to check which tasks are really open. Please keep an eye on #787

**Closed by Gummibeer** 2021-04-27 08:57 UTC
Labels: enhancement, help wanted, revisit for next major version
