### ISSUE TITLE
multi tenant database

### ISSUE THREAD

**Issue by repzlaw** [spatie/laravel-activitylog#778] opened 2020-09-09 09:31 UTC
i run a multi tenant database using inertia and laravel and vue
when i include use spatie in my models that are under the namespace App (Models in App directory), it works.
But when i use it in my models under the namespace App/Tenant (Models in App/Tenant directory), it doesnt work.
please why is this?

here is the code

<?php

namespace App\Tenant;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Spatie\Activitylog\Traits\LogsActivity;

class School extends Model
{
    use LogsActivity;
   

    protected $fillable = [
        'sch_name', 'sch_title',
        'sch_email', 'sch_phone',
        'sch_address', 'sch_type',
        'image', 'lga_id ',
        'country',
        'incorp',
    ];

    protected static $logFillable = true;
    }

**Comment by repzlaw** [comment] 2020-09-09 10:12
<?php

namespace App\Tenant;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Spatie\Activitylog\Traits\LogsActivity;

class School extends Model
{
    use LogsActivity;
    // protected $guarded = [];

    protected $fillable = [
        'sch_name', 'sch_title',
        'sch_email', 'sch_phone',
        'sch_address', 'sch_type',
        'image', 'lga_id ',
        'country',
        'incorp',
    ];

    protected static $logFillable = true;
    }

**Comment by repzlaw** [comment] 2020-09-09 10:13
<?php

namespace App\Tenant;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Spatie\Activitylog\Traits\LogsActivity;

class School extends Model
{
    use LogsActivity;
    // protected $guarded = [];

    protected $fillable = [
        'sch_name', 'sch_title',
        'sch_email', 'sch_phone',
        'sch_address', 'sch_type',
        'image', 'lga_id ',
        'country',
        'incorp',
    ];

    protected static $logFillable = true;
   }

**Comment by Gummibeer** [comment] 2020-09-12 20:59
Duplicate of #779

**Closed by Gummibeer** 2020-09-12 20:59 UTC
Labels: duplicate
