### ISSUE TITLE
NO Causer Id when use deleted

### ISSUE THREAD

**Issue by mangao05** [spatie/laravel-activitylog#597] opened 2019-09-24 02:48 UTC
this is my Product Model

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;

class Products extends Model
{
    use SoftDeletes, LogsActivity;

    protected $guarded = [];
    protected static $logUnguarded = true;
    public function subcategory()
    {
        return $this->belongsTo(SubCategory::class, 'subcategory_id', 'id');
    }

    public function product_details(){
        return $this->hasMany(ProductDetails::class, 'product_id', 'id');
    }

    public function product_images(){
        return $this->hasMany(ProductImages::class, 'product_id', 'id');
    }

    public function order_details(){
        return $this->hasMany(OrderDetails::class);
    }
}
```

this is my delete function 
`$products->product_details()->delete();`

![Screenshot_15](https://user-images.githubusercontent.com/31975866/65477301-7d5b6080-deb8-11e9-9437-c1b37486dbe8.png)

**Comment by Gummibeer** [comment] 2019-09-24 07:31
Hey,

first of all the model that gets deleted is `ProductDetails` not `Product`. But you also don't delete the model via model method but the DB row via query builder.
That's why no event is triggered and the package can't log an activity.
The difference is if you use your relationship method as method or property.
If you want to log activity for every detail you have to use:

```php
$product->product_details->each->delete();
```

Or you log it as a single activity and use a custom activity via `activity()` helper function.

**Comment by mangao05** [comment] 2019-09-24 08:03
> Hey,
> 
> first of all the model that gets deleted is `ProductDetails` not `Product`. But you also don't delete the model via model method but the DB row via query builder.
> That's why no event is triggered and the package can't log an activity.
> The difference is if you use your relationship method as method or property.
> If you want to log activity for every detail you have to use:
> 
> ```
> $product->product_details->each->delete();
> ```
> 
> Or you log it as a single activity and use a custom activity via `activity()` helper function.

oh sorry sir, I've put the wrong code. This is my delete for the product.

`  $Products = Products::findOrfail($id);
        $Products->delete();`

**Comment by Gummibeer** [comment] 2019-09-24 08:14
And do you call it in a controller with a logged in user? Or somewhere in a queue, console command?

**Comment by mangao05** [comment] 2019-09-24 08:22
> And do you call it in a controller with a logged in user? Or somewhere in a queue, console command?

Actually sir, I'm using the default function whereas I'm just using the **LogsActivity** in the model. It's working in other function aside from delete. It is saving but no **causer_id** .

![Screenshot_16](https://user-images.githubusercontent.com/31975866/65494357-42bcec80-dee7-11e9-9fab-32400bf35b29.png)

**Comment by mangao05** [comment] 2019-09-24 08:23
> > And do you call it in a controller with a logged in user? Or somewhere in a queue, console command?
> 
> Actually sir, I'm using the default function whereas I'm just using the **LogsActivity** in the model. It's working in other function aside from delete. It is saving but no **causer_id** .
> 
> ![Screenshot_16](https://user-images.githubusercontent.com/31975866/65494357-42bcec80-dee7-11e9-9fab-32400bf35b29.png)

as you can see sir, didnt work in updated too when i Update the user,

**Comment by Gummibeer** [comment] 2019-09-24 08:28
I meant do you call the `delete()` or `update()` method in your controller/web runtime or in console one? And if someone is really logged in?
https://github.com/spatie/laravel-activitylog/blob/89bbdbea8f085d72ba7513af989e2e54366f5794/src/ActivityLogger.php#L189-L200
This method is responsible to set the default causer. If you add a `dd($this->auth->guard($this->authDriver)->user());` in the `if` you can see which user is resolved by the used guard.
If it's `null` there the problem is in your auth procedure.

**Comment by mangao05** [comment] 2019-09-24 08:33
> I meant do you call the `delete()` or `update()` method in your controller/web runtime or in console one? And if someone is really logged in?
> https://github.com/spatie/laravel-activitylog/blob/89bbdbea8f085d72ba7513af989e2e54366f5794/src/ActivityLogger.php#L189-L200
> 
> 
> This method is responsible to set the default causer. If you add a `dd($this->auth->guard($this->authDriver)->user());` in the `if` you can see which user is resolved by the used guard.
> If it's `null` there the problem is in your auth procedure.

I call it in my Controller sir.

**Closed** 2020-01-27 11:03 UTC

**Comment by vipertecpro** [comment] 2022-07-27 16:43
ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh i get it now ....so i was using api to create and update from salesforce which doesn't come under auth that's way i was getting causer_type and causer_id null. 
So in my case i am using api so how can i set default causer_type and causer_id  in my Model. 
Please help me. THANK YOU.

**Comment by madurapa** [comment] 2024-01-21 23:35
> ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh i get it now ....so i was using api to create and update from salesforce which doesn't come under auth that's way i was getting causer_type and causer_id null. So in my case i am using api so how can i set default causer_type and causer_id in my Model. Please help me. THANK YOU.

you can set the logged-in user as the cause
