### ISSUE TITLE
Problem with model update hook.

### ISSUE THREAD

**Issue by zolotov88** [spatie/laravel-activitylog#528] opened 2019-05-15 04:42 UTC
I got in properties and all fields that have default values in migrations and have not been changed since model was created. 
```
"properties": {
    "a": "New",
    "b": "Default", // $table->string('b')->default('Default'); 
    "c": "Default", // $table->string('c')->default('Default'); 
    "d": "Default", // $table->string('d')->default('Default'); 
    "updated_at": "2019-05-15 03:26:10"
},
"old": {
    "a": "Old",
    "b": null, // ???
    "c": null, // ???
    "d": null, // ???
    "updated_at": "2019-05-15 03:25:53"
}
```
And like so every update.

**Comment by Gummibeer** [comment] 2019-05-15 06:10
We run on `updated` so the model contains the new values (DB default). Compared to the old attributes they have changed.
But the update after this shouldn't contain these values because they are already default!?

**Comment by Zolotov88** [comment] 2019-05-15 06:30
Compared to the old attributes they have not changed. I can change "a" attribute (any attrbute without default value) any times, and every time I will get 
```
"properties": {
    "a": "New",
    "b": "Default", // $table->string('b')->default('Default'); 
    "c": "Default", // $table->string('c')->default('Default'); 
    "d": "Default", // $table->string('d')->default('Default'); 
    "updated_at": "2019-05-15 03:26:10"
},
"old": {
    "a": "Old",
    "b": null, // ???
    "c": null, // ???
    "d": null, // ???
    "updated_at": "2019-05-15 03:25:53"
}
```
even if `protected static $logOnlyDirty = true;`
I will get them while I will not change them.  
After `$model->update(["b" => "Not Default", "c" => "Not Default", "d" => "Not Default"])` I get
```
"properties": {
    "a": "New",
    "b": Not "Default",
    "c": "Not Default",
    "d": "Not Default",
    "updated_at": "2019-05-15 03:26:10"
},
"old": {
    "a": "Old",
    "b": null, // ???
    "c": null, // ???
    "d": null, // ???
    "updated_at": "2019-05-15 03:25:53"
}
```
Then it work as expected.
I'm using pgsql, if it important

**Comment by Gummibeer** [comment] 2019-05-15 07:02
Could you provide a full code example (model, create & update call) or better a failing unittest?

With the logged changes I have to say that it's right what the package does. `null` and `"default"` are different so they have changed.

**Comment by Zolotov88** [comment] 2019-05-15 11:56
Example migration:
```
public function up()
{
    Schema::create('users', function (Blueprint $table) {
        $table->increments('user_id');
        $table->string('name');
        $table->string('email')->unique();
        $table->string('login')->nullable();
        $table->string('currency')->default('RUB');
        $table->text('description')->nullable();
        $table->string('password');
        $table->rememberToken();
        $table->timestamps();
        $table->softDeletes();
    });
}
```

Example model:
```
<?php
namespace App\Models;

use \Hash;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Activitylog\Traits\CausesActivity;
use Spatie\Activitylog\Traits\LogsActivity;
use Tymon\JWTAuth\Contracts\JWTSubject;

/** @mixin \Barryvdh\LaravelIdeHelper\Eloquent */

class User extends Authenticatable implements JWTSubject
{
    use Notifiable, SoftDeletes, LogsActivity, CausesActivity;

    /**
     * @var integer ID key
     */
    public $primaryKey = 'user_id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'login',
        'currency',
        'description',
        'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token'
    ];

    protected static $logAttributes = ['*'];

    protected static $logAttributesToIgnore = [
        'password',
        'remember_token',
        'updated_at'
    ];

    protected static $logOnlyDirty = true;


    /**
     * Automatically creates hash for the user password.
     *
     * @param  string  $value
     * @return void
     */
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }
}
```
Unexpected behavior:
```
 $ php artisan tinker
Psy Shell v0.9.9 (PHP 7.3.4 — cli) by Justin Hileman
>>> $user = User::create([
            'name' => 'Test',
            'email' => 'test@email.com',
            'password' => '123456'
        ])
[!] Aliasing 'User' to 'App\Models\User' for this Tinker session.
=> App\Models\User {#3106
     name: "Test",
     email: "test@email.com",
     updated_at: "2019-05-15 11:47:04",
     created_at: "2019-05-15 11:47:04",
     user_id: 1,
   }
>>> $user->update(["description" => "New description"])
=> true
>>> $user->update(["description" => "Another new description"])
=> true
>>> Spatie\Activitylog\Models\Activity::latest()->limit(3)->get()->reverse()->all()
=> [
     2 => Spatie\Activitylog\Models\Activity {#3101
       id: 1,
       log_name: "default",
       description: "created",
       subject_id: 1,
       subject_type: "App\Models\User",
       causer_id: null,
       causer_type: null,
       properties: "{"attributes":{"user_id":1,"name":"Test","email":"test@email.com","login":null,"currency":"RUB","description":null,"created_at":"2019-05-15 11:47:04","deleted_at":null}}",
       created_at: "2019-05-15 11:47:04",
       updated_at: "2019-05-15 11:47:04",
     },
     1 => Spatie\Activitylog\Models\Activity {#3100
       id: 2,
       log_name: "default",
       description: "updated",
       subject_id: 1,
       subject_type: "App\Models\User",
       causer_id: null,
       causer_type: null,
       properties: "{"attributes":{"currency":"RUB","description":"New description"},"old":{"currency":null,"description":null}}",
       created_at: "2019-05-15 11:47:24",
       updated_at: "2019-05-15 11:47:24",
     },
     0 => Spatie\Activitylog\Models\Activity {#3094
       id: 3,
       log_name: "default",
       description: "updated",
       subject_id: 1,
       subject_type: "App\Models\User",
       causer_id: null,
       causer_type: null,
       properties: "{"attributes":{"currency":"RUB","description":"Another new description"},"old":{"currency":null,"description":"New description"}}",
       created_at: "2019-05-15 11:47:28",
       updated_at: "2019-05-15 11:47:28",
     },
   ]
```
When model was created `"currency":"RUB"`, but after every update in old `"currency":null`. I think it is unexpected behavior.

**Comment by Gummibeer** [comment] 2019-05-15 13:16
Ok, the problem is related to eloquent and not this package.

I've created a failing unittest in #530 (first commit) and fixed it in the last commit.

The problem is that eloquent doesn't refresh the model after a save. So the `currency` attributes stays `null` after creation. That's why the column occurs all the time in the changes.

**Comment by Zolotov88** [comment] 2019-05-16 00:06
Eloquent doesn't refresh the model fields. So it was constantly. I do not think that фfter so much time this behavior will be changed. You can use somesithg like `$model->getChanges()` insted get diff of model fields after and before save in this packadge and it will work right.

**Comment by Gummibeer** [comment] 2019-05-16 06:51
I've found something in our package that could cause it - I will try if it's the reason.
We fresh the model before we clone it.

**Comment by Gummibeer** [comment] 2019-05-16 12:08
@freekmurze the only way I found is to call `refresh()` instead of `fresh()` in `\Spatie\Activitylog\Traits\DetectsChanges::attributeValuesToBeLogged()`.

But this would change the model used by the developer in it's app context (what is needed to have the DB default in the attributes after a save/create and know about it in a following save/update call.
Which is the only case where it doesn't behave like expected.
For me this is a super rare case - so I could live with the solution to expect the developer to refresh his model if it's saved and the database could change the values (DB triggers would be also such a case).
In opposit I think that refreshing the general model instance could lead to much more trouble.

**Comment by therour** [comment] 2019-07-09 14:34
Usually when i have default value in migration, I also add the default `$attributes` in the model, so the model has the default value even it is not saved..

```
// in Model Class

protected $attributes = [
    'currency' => 'RUB',
];
```

**Comment by Gummibeer** [comment] 2020-09-16 15:17
After getting into this myself and googling the 💩 out of Laracast the common solution seems to add the default values as `$attributes` property - like suggested by @therour .

As there's no way for us to detect the default values or that there are some at all I will close this with several provided solutions.

**Closed by Gummibeer** 2020-09-16 15:17 UTC
Labels: bug, help wanted

**Comment by raimondsL** [comment] 2023-05-10 05:57
It appears that default values, including null, have to be added as `$attributes`
