### ISSUE TITLE
Delete event not Logged on 1.6 version

### ISSUE THREAD

**Issue by diogomascarenha** [spatie/laravel-activitylog#47] opened 2016-08-12 22:11 UTC
I ran the command "composer update" and "laravel-activitylog" updated to version 1.6.0
The event recording the record deletion log was not executed, the record was deleted from the Model table, but was not included in the "activity_log" table.

**Comment by freekmurze** [comment] 2016-08-13 22:03
The test seems to confirm that record deletion logging works. Could you post a failing test?

Or maybe if you post your model and used code, I can see what's wrong.

**Comment by sineld** [comment] 2016-08-22 11:43
+1 for v. ^1.7 with Laravel 5.3 RC1

**Comment by freekmurze** [comment] 2016-08-22 12:34
I'll tag a new version when Laravel 5.3 gets released (probably tomorrow)

**Comment by sunnyjayjay** [comment] 2016-09-22 09:35
I have the same problem. No delete logging is occurring. I am on Laravel 5.2.

**Comment by freekmurze** [comment] 2016-09-22 09:46
The test seems to confirm that this should work: https://github.com/spatie/laravel-activitylog/blob/master/tests/DetectsChangesTest.php#L83-L96

Could you PR a failing test for me to fix?

**Comment by sineld** [comment] 2016-09-22 09:56
Still not logging deletes after update to Laravel 5.3.10 and Avtivity log 1.9.1

**Comment by sunnyjayjay** [comment] 2016-09-22 09:59
Sorry, don't quite understand what you want me to do when you say "PR a failing test for me to fix". I am using the trait in my models and creates and updates all log fine - but nothing for deletes.

**Comment by freekmurze** [comment] 2016-09-22 10:05
Well, my automated tests seem to indicated that a deletion is logged. It would help me to track down and solve the bug if you can create a test that illustrates that a deletion is not logged.

**Comment by freekmurze** [comment] 2016-09-24 12:25
If you take a look at [the deletion test](https://github.com/spatie/laravel-activitylog/blob/master/tests/DetectsChangesTest.php#L83-L96) you'll see that it does exactly the same thing that you are describing.

In my projects this seems to work as well.

Could you please check what you are doing differently from the test? If the test contains an error let me know.

**Comment by sunnyjayjay** [comment] 2016-09-24 15:35
I am sorry but your test bears no resemblance to what I am trying to do or what your documentation suggests is possible. I am simply attaching your trait to the model and then using LogsActivity. I have proved happily that a create and an update are both logged perfectly by this means. However a delete does not write anything to the log.

This is clearly a bug in the model attachment behaviour.

**Comment by freekmurze** [comment] 2016-09-24 16:08
The test [sets up a model that uses the LogsActivity trait](https://github.com/spatie/laravel-activitylog/blob/master/tests/DetectsChangesTest.php#L21). Then an new instance of the model is [created and deleted](https://github.com/spatie/laravel-activitylog/blob/master/tests/DetectsChangesTest.php#L86-L88).

Please help me to understand what you are doing differently.

**Comment by freekmurze** [comment] 2016-09-24 16:09
If you have a fix in our code for the problem you are experience I'd gladly take a look at a PR.

**Comment by xcaptain** [comment] 2016-09-25 11:37
@freekmurze I just modified the delete event test and breaked it, It's wired can you take a look at it?

**Comment by freekmurze** [comment] 2016-09-25 15:59
@xcaptain thanks for submitting a test. You were using a model which does not use the `LogsActivity` trait, so it a failure was expected there.

**Comment by xcaptain** [comment] 2016-09-26 03:03
@freekmurze please review my new pull request https://github.com/spatie/laravel-activitylog/pull/77

**Comment by freekmurze** [comment] 2016-09-26 19:30
Thanks again @xcaptain for demonstrating that there is indeed an issue.

I've pushed a fix to the master branch. Those with problems, could you try the current master version and let me know if the deletion is logged now?

**Comment by sineld** [comment] 2016-09-26 21:21
Did not work for me, still not logging deletes.

**Comment by freekmurze** [comment] 2016-09-26 21:50
@sineld could you tell me what you are doing differently from [this test](https://github.com/spatie/laravel-activitylog/blob/master/tests/LogsActivityTest.php#L55-L69)?

**Comment by xcaptain** [comment] 2016-09-27 02:41
@freekmurze delete log on dev-master works for me, I think this bug fixed 👍

**Comment by sineld** [comment] 2016-09-27 05:06
@freekmurze logging on dev-master branch works for me too. Finally fixed, thank you.

**Comment by freekmurze** [comment] 2016-09-27 07:34
Fix has been tagged as `v1.9.2`.

**Closed by freekmurze** 2016-09-27 07:34 UTC

**Comment by sunnyjayjay** [comment] 2016-09-27 10:11
At last I can confirm that this is fixed.
