### ISSUE TITLE
Activity logging twice!

### ISSUE THREAD

**Issue by ScriptMint** [spatie/laravel-activitylog#387] opened 2018-06-06 09:31 UTC
Hi,

I am using Laravel 5.6.24, PHP Version is 7.1.9

I have put LogActivity traits in Model. Here is my model:
```
        class Backup extends Model
        {
            use LogsActivity;
            protected $fillable = [];
            protected $primaryKey = 'id';
            protected $table = 'backups';
            protected static $ignoreChangedAttributes = ['updated_at'];
            protected static $logAttributes = ['file'];
            protected static $logName = 'backup';
            protected static $logOnlyDirty = true;
        }
```

and Here is my controller function "download" 

```
        public function download($id)
        {
            $backup = $this->repo->findOrFail($id);

            try {
                \Storage::exists('uploads/backup/'.$backup->file);
            } catch (\Exception $e) {
            }

            activity('backup')->on($backup)->log('downloaded');

            $download_path = storage_path('app/uploads/backup/'.$backup->file);

            return response()->download($download_path);
        }
```

While the download doesn't make change in the table row so nothing is logged when I comment activity log function in download function. But when I uncomment, it logs twice as below:

![img](https://user-images.githubusercontent.com/31760604/41029802-4a92517a-699a-11e8-873e-6205af7eb09a.JPG)

what can be the issue?

**Comment by freekmurze** [comment] 2018-06-09 09:40
Could it be that the row gets updated twice? Maybe though a timestamp update or something like that?

The tests indicate that the package itself has no issues with double logging.

**Comment by DanielRTRD** [comment] 2018-08-09 20:44
I have this problem too, but I know what it is causing it. I have a last_activity that gets updated 'every' page refresh. Do you have something like that?

**Comment by freekmurze** [comment] 2018-08-13 11:09
Closing this, as this problem is probably caused by something app specific and not this package.

**Closed by freekmurze** 2018-08-13 11:09 UTC
