### ISSUE TITLE
Stop using Guard Provider directly

### ISSUE THREAD

**Issue by falnyr** [spatie/laravel-activitylog#716] opened 2020-04-13 22:53 UTC
Hi, I'm updating a legacy codebase L5.1 -> L7 that has this package installed. I had to rework the oAuth package from some legacy to [laravel-passport](https://laravel.com/docs/7.x/passport).

Now I'm having an issue with Passport not having the right `UserProvider` that the `normalizeCauser` method is using.

The method is [getting the provider](https://github.com/spatie/laravel-activitylog/blob/master/src/ActivityLogger.php#L190) but the provider is empty because when Laravel Passport is instantiating the guard it [uses the callback and not providing the UserProvider](https://github.com/laravel/passport/blob/8.x/src/PassportServiceProvider.php#L276-L284).

This seems fine for the Passport side of things cause [there is support for the callback](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Auth/RequestGuard.php#L57-L59). 

But the `normalizeCauser` method is trying to access the `Provider` directly, rather than trying to get the resolved `User`.

So the question is, should this:
```php
$guard = $this->auth->guard($this->authDriver);
$provider = method_exists($guard, 'getProvider') ? $guard->getProvider() : null;
$model = method_exists($provider, 'retrieveById') ? $provider->retrieveById($modelOrId) : null;
```

be changed into something like this?:

```php
$guard = $this->auth->guard($this->authDriver);
$model = method_exists($guard, 'user') ? $guard->user() : null;
```

IMHO it would make more sense since the `Guard` needs to implement [Guard contract](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Contracts/Auth/Guard.php)  which has the `user` method.

If it sounds reasonable I'm happy to submit a PR.

**Comment by Gummibeer** [comment] 2020-04-23 12:30
Hey,
thanks for this pretty complete issue! :)

The `$guard->user()` method does something different - because we do not only handle the current logged in user but also a given causer we need a method that can resolve the causer by ID and not only the current one.
You are right that it's a misuse of the auth/guard class. Possibly we should add our own resolver that could be overridden via app service-provider.
As long as it's not breaking I would accept a PR that introduces our own user resolver. And idea would be to put the current logic into the default resolver. So the only changing thing would be that the user can override it.

**Comment by Gummibeer** [comment] 2021-04-27 08:57
I will close this issue even if v4 isn't released yet. But the task itself is done and I want to check which tasks are really open. Please keep an eye on #787

**Closed by Gummibeer** 2021-04-27 08:57 UTC
Labels: enhancement, good first issue, help wanted, revisit for next major version
