### ISSUE TITLE
Using LogsActivity and CausesActivity Traits on Same Model

### ISSUE THREAD

**Issue by kornatzky** [spatie/laravel-activitylog#224] opened 2017-07-21 14:48 UTC
use Spatie\Activitylog\Traits\LogsActivity;
    use Spatie\Activitylog\Traits\CausesActivity;

    class Admin extends Authenticatable
    {
         use Notifiable;
         use CausesActivity;
         use LogsActivity;

Get this error:

(1/1) FatalErrorException
Trait method activity has not been applied, because there are collisions with other trait methods on App\Admin

Does not happen if I use only LogsActivity

**Comment by freekmurze** [comment] 2017-07-21 23:47
Duplicate of #215 

I'll fix this late August when creating v2 that will be L5.5 only.

**Closed by freekmurze** 2017-07-21 23:47 UTC

**Comment by nessimabadi** [comment] 2017-09-09 17:13
Still getting the error on version 2.0 with L5.5.

`Trait method activity has not been applied, because there are collisions with other trait methods on App\User`

**Comment by freekmurze** [comment] 2017-09-09 17:59
I forgot to put my `revisit` label here, so didn't revisit this issue before tagging `v2`.

I'll talk a look before tagging the next major version (might be a while though)

**Comment by freekmurze** [comment] 2026-03-22 09:02
Addressed in v5 (#1452) with renamed methods (`activitiesAsSubject()`, `activitiesAsCauser()`) and a new `HasActivity` combining trait.
