### ISSUE TITLE
Using LogsActivity and CausesActivity on same model

### ISSUE THREAD

**Issue by ads-nicolasey** [spatie/laravel-activitylog#329] opened 2017-12-28 15:55 UTC
**Use Case :** 
- My User causes activity
- I want to see activity performed by user on himself, and admins on a User

**Issue:** 
- There is a collision between the two traits, since activity() methods in traits are named the same way. I am therefore forced to choose between them 
- Cannot make any difference between activity ON object, and activity OF the object. A shame, since this package is fully capable of that distinction.

**Suggestion:** 

Perhaps rename `activity` into `actions` in CausesActivity will allow this kind of use case a simple way. Docs or usage don't even change (or slightly since actions and activity are used the same way).

**Comment by freekmurze** [comment] 2017-12-28 15:58
Duplicate of #224

**Closed by freekmurze** 2017-12-28 15:58 UTC

**Comment by ads-nicolasey** [comment] 2017-12-28 16:01
Thanks @freekmurze 
Any idea of when ?
Let me know if I can be of any help

**Comment by Gummibeer** [comment] 2017-12-28 18:10
as a temp solution for this, #215 & #224 - you can define what you want to use if there are trait conflicts:
http://php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict
This could be a temp solution until it's fixed in package.

As a longtime but breaking solution I suggest to add a trait `HasActivities` so you have three traits you have to use.

**Comment by freekmurze** [comment] 2018-10-15 07:33
I'm accepting a PR that fixes is on the `v3` branch
