### ISSUE TITLE
Activity triggered User update on user logout

### ISSUE THREAD

**Issue by dennis1502** [spatie/laravel-activitylog#449] opened 2018-10-18 17:09 UTC
I noticed that after a user logs out, the LogsActivity Traits is triggered the `updated` event. After some searching I discovered that is caused by the remember_token in the User model, because this will be updated after loggin out.

Now I set the `protected static $logAttributesToIgnore = [ 'remember_token'];` in the User model to ignore the activity, because the logger will attach a new record with `{"attributes":[],"old":[]}` properties in the database. But the `logAttributesToIgnore` is not working, because the record will still be added, but now without properties `[]`

Is there a setting I missed or is it a bug? 
For you info, this is the record which is added:
Before ignoring the `remember_token`

| id | log_name | description | subject_id | subject_type | causer_id | causer_type | properties |
|---|---|---|---|---|---|---|---|
| 42 | user | updated | 1 | Modules\Users\Entities\User | 1 | Modules\Users\Entities\User | {"attributes":[],"old":[]} |

After ignoring the `remember_token`

| id | log_name | description | subject_id | subject_type | causer_id | causer_type | properties |
|---|---|---|---|---|---|---|---|
| 68 | user | updated | 1 | Modules\Users\Entities\User | 1 | Modules\Users\Entities\User | [] |

Thanks!

**Comment by Gummibeer** [comment] 2018-10-18 17:42
I think that it's related to #448 - like said there I can't reproduce it on my local machine.
I will try to reproduce your given example to solve it now and forever.

The method in question should be `shouldLogEvent()`.
https://github.com/spatie/laravel-activitylog/blob/68eb6e65382f94fe86ce5ff6572159f80d024ba9/src/Traits/LogsActivity.php#L107-L125

If you could provide some debug information out of this method (what everything has as value, what it returns and do on) would be great.
Independent I will try to get some details on my own - could be that I need until tomorrow to debug it.

**Comment by Gummibeer** [comment] 2018-10-18 19:53
@dennis1502 I got the solution for you - add this (additional to `$logAttributesToIgnore`) to your Model.
```php
protected static $ignoreChangedAttributes = ['remember_token'];
```

I have to dive deeper into this and why there are two properties for this. One is in the `LogsActivity` and the other in `DetectsChanges` trait. One controls the attributes listed in the `attributes` and `old` arrays and the other if it should create the log or not.
At first this sounds like the same but it doesn't have to be.

**Reason:**
If you have an attribute that shouldn't create a log, if it's the only changed one, but should be listed if another attribute creates a log.
@freekmurze is this the reason? Or is it a mistake and should be fixed to one property?
I will also take a look in the documentation and unittests if there is something missing - tomorrow.

**Comment by dennis1502** [comment] 2018-10-19 06:45
@Gummibeer Thank you so much, that actually worked for me. I checked that file earlier yesterday, but didn't noticed the `ignoreChangedAttributes` I could use. Now it works lik a charm. 

I really don't know the reason yet, maybe @freekmurze can confirm your idea about it. But for now it works! :D

Many thanks!

**Closed** 2018-10-19 07:33 UTC
Labels: question

**Comment by Zolak94** [comment] 2019-09-05 13:07
I'm facing the same problem and the solution provided here didn't help me solve it.

**Comment by Gummibeer** [comment] 2019-09-05 13:36
@Zolak94 I thought your problem is that the causer is empty? Like described in #588

**Comment by Zolak94** [comment] 2019-09-05 13:46
@Gummibeer Yes I do, I also have this problem, on my deploy (live) server whenever a user logs out it's also updated I figured out that remember token is the thing that's changing and triggering that. But your solution with putting `protected static $ignoreChangedAttributes = ['remember_token'];` in my` User.php` model doesn't work. On the other hand, everything works normally on my local machine.

**Comment by Gummibeer** [comment] 2019-09-05 13:48
@Zolak94 do you add it in addition to `protected static $logAttributesToIgnore = [ 'remember_token'];`?

**Comment by Zolak94** [comment] 2019-09-05 13:52
@Gummibeer Yes, I did.

**Comment by Gummibeer** [comment] 2019-09-05 13:55
And you still get an update record for the user? Is there any other changed attribute in the properties listed?

**Comment by Zolak94** [comment] 2019-09-05 13:57
Yeah.

**Comment by Gummibeer** [comment] 2019-09-05 14:00
So where's the bug/problem? If there are other changed properties than the ignored ones - it will create an activity entry.

**Comment by Zolak94** [comment] 2019-09-05 14:05
I'm sorry that I didn't answer fully. Nothing else except `remember_token` changes when a user logs out.

**Comment by Zolak94** [comment] 2019-09-06 07:52
And this is only happening on a live website, not on my local machine.

**Comment by zenepay** [comment] 2024-09-15 12:53
It doen't work for me. It still updated at the logout time. It look strange.
