### ISSUE TITLE
Updated Logs are not saving in database in AWS server

### ISSUE THREAD

**Issue by RezowanaAkter** [spatie/laravel-activitylog#922] opened 2021-07-12 07:26 UTC
**Describe the bug**
Created and deleted logs are saving in DB in AWS server but for Updated logs are not saving in DB in AWS server but It is saving in Local environment perfectly. I am using Activity log in Model. Activity log is called in Every Model.

**Expected behavior**
Updated logs should be saved in AWS Server. 

**Versions (please complete the following information)**
- PHP: 7.2
- Database: MySQL
- Laravel: 6
- Package: spatie/laravel-activitylog

**Comment by lagomf** [comment] 2021-11-19 14:31
Are you using a AWS Database with replication like Aurora? Because I found a similar problem in my project while using AWS Aurora where the Activity Log used the $model->fresh() method to detect changes in the model atributes, but because I had replication (DB reader and writer in separate endpoints) the fresh() method read the replica database faster than the replication process, so when I updated a model, it read the replica before the changes propagated  and did not apply it to the activity log.

**Comment by AlexVanderbist** [comment] 2022-04-07 19:46
@lagomf interesting issue! Was this Aurora's behaviour or Laravel's behaviour caused by the read/write database configs. I've used Aurora with this package before but never experienced issues (unless we didn't notice).

I'm going to close this issue for now. If anyone is still experiencing this issue, feel free to create a new issue with a link back to this one and if at all possible, a way to replicate the issue (I'm happy to deploy a test repo on AWS to figure this out).

**Closed by AlexVanderbist** 2022-04-07 19:46 UTC
Labels: help wanted, question
